social:
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}
- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}


menu:
- { url: '/', text: 'Home' }
- { url: '/about-me/', text: 'About Me' }
- { url: '/blog/', text: 'Blog Posts' }